apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:8
          name: mysql-db
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
#              value: sasa
              valueFrom:
                secretKeyRef:
                  name: msvc-usuarios
                  key: password
            - name: MYSQL_DATABASE
#              value: msvc_usuarios
              valueFrom:
                configMapKeyRef:
                  name: msvc-usuarios
                  key: database
          volumeMounts:
            - name: data-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: mysql-pvc

#          hostPath:
#            path: /var/lib/mysql
#            type: DirectoryOrCreate