apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresomar14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - image: postgres:14-alpine
          name: postgresomar14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: password
#              value: sasa
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
#              value: postgres
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
#          hostPath:
#            path: /var/lib/postgresql/data
#            type: DirectoryOrCreate