version: "3.8"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  serverPostgresDocker:
    container_name: serverPostgresDocker
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DATABASE: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    image: usuarios:latest
    ports:
      - "9001:8001"
    env_file:
      - ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql-db
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    image: cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "9002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - serverPostgresDocker
    restart: always

volumes:
  data-mysql:
    name: data-mmysql
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring