apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-24T02:44:39Z"
  labels:
    app: msvc-usuarios
  name: msvc-usuarios
  namespace: default
  resourceVersion: "167934"
  uid: 9388f916-0055-4820-b2d5-95b7fa442330
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.188.144
  clusterIPs:
  - 10.103.188.144
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30743
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: msvc-usuarios
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
