apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql-db"
  db_port: "3306"
  database: msvc_usuarios
#  username: root
#  password: sasa
  curso_url: "msvc-cursos:8002"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgresomar14"
  db_port: "5432"
  database: msvc_cursos
#  username: postgres
#  password: sasa
  usuario_url: "msvc-usuarios:8001"